"""Bake the base-ID font into a small JS table (server/static/vendor/glyphs.js).

Only the 32 Crockford base32 characters the ID codes use are extracted, from
DejaVu Sans Mono Bold (Bitstream Vera licence: the notice ships alongside as
vendor/DEJAVU-LICENSE.txt). Curves are flattened to polylines; coordinates
are normalised to cap height 1 with the baseline at y = 0, so the app needs
no font parsing at runtime.

  .venv/bin/python scripts/bake_glyphs.py
"""
import json
import math
import os
import shutil

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
LICENSE = "/usr/share/doc/fonts-dejavu-core/copyright"
CHARS = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "server", "static", "vendor", "glyphs.js")


class FlatPen(BasePen):
    """Collects closed contours as point lists, flattening curves."""

    def __init__(self, glyphset, step):
        super().__init__(glyphset)
        self.step, self.contours, self.cur = step, [], []

    def _moveTo(self, p):
        self.cur = [p]

    def _lineTo(self, p):
        self.cur.append(p)

    def _curveToOne(self, p1, p2, p3):
        p0 = self.cur[-1]
        n = self._segments(p0, p1, p2, p3)
        for i in range(1, n + 1):
            t = i / n
            mt = 1 - t
            self.cur.append((mt**3 * p0[0] + 3 * mt * mt * t * p1[0] + 3 * mt * t * t * p2[0] + t**3 * p3[0],
                             mt**3 * p0[1] + 3 * mt * mt * t * p1[1] + 3 * mt * t * t * p2[1] + t**3 * p3[1]))

    def _qCurveToOne(self, p1, p2):
        p0 = self.cur[-1]
        n = self._segments(p0, p1, p2)
        for i in range(1, n + 1):
            t = i / n
            mt = 1 - t
            self.cur.append((mt * mt * p0[0] + 2 * mt * t * p1[0] + t * t * p2[0],
                             mt * mt * p0[1] + 2 * mt * t * p1[1] + t * t * p2[1]))

    def _segments(self, *pts):
        # control-polygon length bounds the curve length; chord error ~ L^2/(8R)
        L = sum(math.dist(a, b) for a, b in zip(pts, pts[1:]))
        return max(2, min(24, math.ceil(L / self.step)))

    def _closePath(self):
        if len(self.cur) > 1 and math.dist(self.cur[0], self.cur[-1]) < 1e-9:
            self.cur.pop()
        if len(self.cur) >= 3:
            self.contours.append(self.cur)
        self.cur = []

    _endPath = _closePath


def main():
    font = TTFont(FONT)
    gs = font.getGlyphSet()
    cmap = font.getBestCmap()
    # older OS/2 tables have no cap height: measure the "H" glyph instead
    cap = getattr(font["OS/2"], "sCapHeight", 0) or font["glyf"][cmap[ord("H")]].yMax
    adv = font["hmtx"][cmap[ord("0")]][0]
    out = {}
    for ch in CHARS:
        pen = FlatPen(gs, step=cap * 0.08)
        gs[cmap[ord(ch)]].draw(pen)
        out[ch] = [[round(v / cap, 4) for pt in c for v in pt] for c in pen.contours]
    data = {"font": "DejaVu Sans Mono Bold (subset)", "capHeight": 1.0,
            "advance": round(adv / cap, 4), "chars": out}
    js = ("/* Glyph outlines for the base ID codes: the 32 Crockford base32\n"
          "   characters from DejaVu Sans Mono Bold, flattened to polygons and\n"
          "   normalised to cap height 1 (baseline y = 0). Generated by\n"
          "   scripts/bake_glyphs.py -- do not edit by hand.\n"
          "   Copyright (c) 2003 by Bitstream, Inc. All Rights Reserved. Bitstream\n"
          "   Vera is a trademark of Bitstream, Inc. DejaVu changes are in public\n"
          "   domain. Licence: see DEJAVU-LICENSE.txt next to this file. */\n"
          "self.HMS_GLYPHS = " + json.dumps(data, separators=(",", ":")) + ";\n")
    with open(OUT, "w") as f:
        f.write(js)
    shutil.copy(LICENSE, os.path.join(os.path.dirname(OUT), "DEJAVU-LICENSE.txt"))
    pts = sum(len(c) // 2 for g in out.values() for c in g)
    print(f"wrote {OUT}: {len(out)} glyphs, {pts} points, {os.path.getsize(OUT)} bytes")


if __name__ == "__main__":
    main()
